export default {
  login: "ronaknavadiya",
  id: 52342249,
  node_id: "MDQ6VXNlcjUyMzQyMjQ5",
  avatar_url: "https://avatars.githubusercontent.com/u/52342249?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ronaknavadiya",
  html_url: "https://github.com/ronaknavadiya",
  followers_url: "https://api.github.com/users/ronaknavadiya/followers",
  following_url:
    "https://api.github.com/users/ronaknavadiya/following{/other_user}",
  gists_url: "https://api.github.com/users/ronaknavadiya/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/ronaknavadiya/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ronaknavadiya/subscriptions",
  organizations_url: "https://api.github.com/users/ronaknavadiya/orgs",
  repos_url: "https://api.github.com/users/ronaknavadiya/repos",
  events_url: "https://api.github.com/users/ronaknavadiya/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/ronaknavadiya/received_events",
  type: "User",
  site_admin: false,
  name: "Ronak Navadiya",
  company: "Student",
  blog: "",
  location: "Surat,India",
  email: null,
  hireable: null,
  bio: "Enthusiastic learner of React and android applications.",
  twitter_username: null,
  public_repos: 12,
  public_gists: 0,
  followers: 2,
  following: 4,
  created_at: "2019-06-29T05:59:11Z",
  updated_at: "2021-03-06T05:26:03Z",
};
